# Generated by Django 4.2.1 on 2023-08-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NinepmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberVerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('phone_number', models.CharField(max_length=20)),
                ('token_key', models.CharField(max_length=255, unique=True)),
                ('token_value', models.CharField(max_length=1024)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('NOT_VERIFIED', 'NOT_VERIFIED')], max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CLOSED', 'CLOSED')], max_length=30)),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=30, null=True)),
                ('expired_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_in_phone_number_verification_request', to='model_ninepm.ninepmuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_value', models.CharField(max_length=1024)),
                ('retry_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CLOSED', 'CLOSED')], max_length=30)),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=30, null=True)),
                ('otp_expired_at', models.DateTimeField()),
                ('send_otp_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_in_login_request', to='model_ninepm.ninepmuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('my_phone_number', models.CharField(max_length=20)),
                ('phone_number_of_crush', models.CharField(max_length=20)),
                ('reminiscent_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('MATCHED', 'MATCHED'), ('CONNECTING', 'CONNECTING'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=30)),
                ('start_at', models.DateTimeField()),
                ('matched_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('crush_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crush_user_in_crush', to='model_ninepm.ninepmuser')),
                ('my_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_user_in_crush', to='model_ninepm.ninepmuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('SEEN', 'SEEN')], default='SENT', max_length=30)),
                ('message', models.CharField(max_length=1024)),
                ('start_at', models.DateTimeField()),
                ('my_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_user_in_message', to='model_ninepm.ninepmuser')),
                ('user_of_crush', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_of_crush_in_message', to='model_ninepm.ninepmuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FcmTokenMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('db_log_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB log created at')),
                ('db_log_updated_at', models.DateTimeField(auto_now=True, verbose_name='DB log updated at')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('device_token', models.CharField(max_length=255)),
                ('fcm_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_in_fcm_token_membership', to='model_ninepm.ninepmuser')),
            ],
            options={
                'unique_together': {('device_token', 'fcm_token')},
            },
        ),
    ]
